### ISSUE TITLE
Scenes and automations don't work

### ISSUE THREAD

**Issue by TheLastGimbus** [outadoc/home-slide-android#345]
**Describe the bug**
My lights and "help switches" work fine, but setting scene doesn't take any effect - it is just disabled all the time, and clicking it does nothing

Adding automations is more interesting. They don't work, and also disappear after few seconds :shrug:

**To Reproduce**
1. Add youselve some scene
2. Click it
3. No results

**Expected behavior**
Scene should be "turned on" aka applied

**Smartphone (please complete the following information):**
 - Device: de-Googled Pixel 1
 - OS: LineageOS 17 (android 10) + microG
 - App Version: 1.5.10

**Additional context**
I tried it both on my wifi (local `192.168` link) and on data (global `https://` link). Same thing on both :confused: 

// By the way, I just want to say that I don't know how could I live without this app - thank you **SO MUCH** for this :heart:

**Comment by outadoc** [comment]
Hi! I didn't add support for the `scene` domain yet, but it looks simple enough to do so it's on the list 🙂

Thanks for your support! ❤️
