### ISSUE TITLE
Could not find a paired wear os device

### ISSUE THREAD

**Issue by elblogbruno** [outadoc/home-slide-android#354]
Hello , thanks for such nice application. The thing is I can get to install the app on my watch. It is a LG G Watch with Android wear 1.5.0, and the app shows this message; Could not find a paired wear os device

Maybe it is because the watch is old? 

Thanks
Bruno

**Comment by outadoc** [comment]
Hi @elblogbruno, yes, unfortunately Android Wear 1.x is not supported, as it doesn't support standalone apps. Google has recently made even more efforts to deprecate the old model, so I won't be able to support this.

**Comment by elblogbruno** [comment]
Thanks for answering!
Great app I use it everyday!
