### ISSUE TITLE
Wear OS app does not work via Bluetooth

### ISSUE THREAD

**Issue by zeroos** [outadoc/home-slide-android#355]
**Describe the bug**
I have the wear os app installed on my watch that connects via both wifi and bluetooth. In order to save energy by default it is connected via Bluetooth. After I just installed the app it was not working, it complained that it cannot connect to localhost. However when I forced wifi connection, everything was fine. I do not want to have the wifi turned on all the time, because it would drain my battery too fast.

**To Reproduce**
1. Install the app
2. Make sure wifi is not connected
3. Try to run the app
4. Connection error

**Expected behavior**
I would expect the app to work both via wifi and bluetooth

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: Fossil Gen 5
 - OS: Wear OS 2.21
 - App Version: 1.5.11

**Comment by zeroos** [comment]
Thanks for creating the app and making it open source! It's really awesome how the community around Home Assistant is developing.

I've investigated a bit and it seems that when Wear OS is connected via bluetooth the access to Internet is proxied on the phone, which means that Wear OS does not have access to local network.

I've forked your project and somehow addressed the issue in my fork: https://github.com/zeroos/home-slide-android

Whenever the app opened, the Wifi connection is requested. Probably not the best solution but sort-of works for me. If you'd be interested in pulling something in this direction into the project I could try to improve it by actually waiting for the connection to be established before making requests (for now you always get first an error, but then the app is working) and submit a pull request.

If you are thinking about some other solution, I could also try to help, but I'm not very experienced with Kotlin/Wear OS. Probably ideal would be to actually send commands via bluetooth if wifi is off and then the phone could forward them to HA.

**Comment by outadoc** [comment]
Hi @zeroos, sorry I'm responding to this so late - thank you for your investigation!

This looks like a valid solution - Wear OS seems to be lacking in documentation (surprisingly) and I've suspected something like this might be happening but never confirmed it (without even mentioning how hard it is to test, when even `adb` is flaky...).

I'm surprised that calls to the Internet would be proxied but not calls to the local network. But that seems very possible and would explain the behavior.

> Whenever the app opened, the Wifi connection is requested.

I think we could take this even further by only requesting Wi-Fi when trying to reach the local HASS address. But that would mean always testing the remote address first, at least on the watch.

I'll try to refactor all of this a little, and then I think we'll be able to integrate your fix 🙂
