### ISSUE TITLE
Unable to connect to Home Assistant

### ISSUE THREAD

**Issue by seanmccabe** [outadoc/home-slide-android#358]
App will not allow connection to home assistant, regardless if I use remote or local address (DNS name, or IP) just comes up with red exclamation mark and button remains unclickable.

**Comment by barrymossel** [comment]
Did you add http/https? Did you add the port number?

**Comment by seanmccabe** [comment]
Yup, tried with and without https (Tho Home Assistant is on https).
With and without the port number. 
No combination works. 
Home Assistant app works, as does browser. 

![Screenshot_20201223-080038_Home Slide](https://user-images.githubusercontent.com/12243212/102923702-154d5d00-44f5-11eb-868e-775c325228b1.jpg)

Are there any log exports etc. I can send to diagnose?

**Comment by seanmccabe** [comment]
Updated the app today, with your implemented fixes. The login button now allows me to press it, but getting the attached error.

![Screenshot_20210322-122045_Home Slide.jpg](https://user-images.githubusercontent.com/12243212/111924419-557aa680-8b09-11eb-9640-42b02cdba990.jpg)

It is a valid cert for the domain, using external access on an actual domain name.
So not self signed.
Internal and external url are the same because of the SSL cert.

**Comment by outadoc** [comment]
@seanmccabe Thanks for your feedback! 🙂 

Did you have to add a root certificate to your device's trust store? If so that would explain it, as Home Slide would have to explicitly trust certificates in the user trust store, and I haven't thought of doing that...

I might just add a checkbox to disable certificate verification, but if we can fix this properly, let's try to do so.

**Comment by seanmccabe** [comment]
> Did you have to add a root certificate to your device's trust store?

No I haven't had to for the home assistant app, nor for browser access.

A couple of other apps like Flic I have to bypass the security certificate verification. So a checkbox to disable certification verification would be good. Imagine helpful for others too.

**Comment by outadoc** [comment]
I suppose so 👍 I'll try to work on that soon, shouldn't be too hard to implement.

**Comment by seanmccabe** [comment]
Update you've pushed out has resolved the issue.
Finally working now :)

**Comment by outadoc** [comment]
Awesome! Thank you for your help @seanmccabe :)
