### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by barrymossel** [outadoc/home-slide-android#359]
**Is your feature request related to a problem? Please describe.**
A lot of dumb lights appear as switches and they show a power plug.

**Describe the solution you'd like**
Ability to choose a mdi per entity.

**Comment by outadoc** [comment]
Hi!

My mindset so far has been to keep this kind of feature out of the app; to achieve this, you can customize the entity from your Home Assistant instance and add an `icon` property to it.

<img width="1178" alt="Screen Shot 2020-12-16 at 16 20 24" src="https://user-images.githubusercontent.com/490651/102368000-acc52400-3fba-11eb-9b5e-2f41ff707e00.png">

This should be reflected in Home Slide.
