### ISSUE TITLE
Improve instance discovery with internal_url and external_url

### ISSUE THREAD

**Issue by outadoc** [outadoc/home-slide-android#376]
**Is your feature request related to a problem? Please describe.**
Host discovery can be a bit unreliable. (see #358)

**Describe the solution you'd like**
Home Assistant now gives us the internal *and* external base URLs, both in mDNS and after the discovery_info has been retrieved. We can use this to setup the instance properly.

**Comment by seanmccabe** [comment]
Do not many of us have home assistant on seperate vlans, or segregated in someway, as such relying on mDNS will not work in these instances

**Comment by outadoc** [comment]
This shouldn't cause problems, mDNS is only used to assist discovery but you'll always be able to enter your instance domain manually 👍
