### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by euinor** [outadoc/home-slide-android#401]
**Describe the bug**
The app finds my home assistant installation correctly (it appears as an option on the initial screen) but if I select it I am taken to a webview page where it says 'not found'.
I'm using duckdns to manage external access and certificates for my instance, so the address is:
https://[nickname].duckdns.org:[port]

**To Reproduce**
Click on the suggested instance on the intial page.
Webview page opens
Text 'not found' appears.

**Expected behavior**
To be taken to a log in page on my home assistant instance.

**Screenshots**
--

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11
 - App Version: 1.6.5

**Additional context**
--

**Comment by euinor** [comment]
I've made some progress: if I open the webview in my android browser (firefox) the web address looks a bit like:
[nickname].duckdns.org/auth/authorize?client_id....
If I add the port to the URL it takes me to a log in page, offering to give https://homeslide.app access to my instance.
Sadly logging in then opens the homeslide app to a blank screen.

Strangely, if I manually enter https://[nickname].duckdns.org:[port] into the Home Assistant URL in the Homeslide app I still get a webview page with 'not found'. Even though it works in the Firefox app.

P.S. Using homeassistant.local or my local IP doesn't work either.

**Comment by outadoc** [comment]
Hi! Can you check what is set up in your Home Assistant instance, in settings, in "General Configuration", under "Internal URL" and "External URL"?

It's possible that the port is missing from there.

**Comment by euinor** [comment]
You nailed it thanks. I added the missing port to the External URL in HA settings, rebooted it. I also force stopped and cleared storage for the HA Slide app and now it all works fine. Thanks for your help!

**Comment by outadoc** [comment]
Glad I could help 🙂
